---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.11.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci

  github_binary_release:
    image: plugins/github-release
    files:
     - bin/*
    checksum:
     - sha256
    secrets: [github_token]
    when:
      branch: master
      event: tag
